### ISSUE TITLE
[README] files that you can ignore - really?

### ISSUE THREAD

**Issue by rofe** [bdelacretaz/helixing#3]
I'm not too sure about this paragraph - I rather think, on the contrary, a dev will gradually start using these as she starts adding custom code (e.g. see https://github.com/adobe/helix-home/blob/getting-started-2.0/getting-started-2.0.md#add-your-own-code). as soon as you start writing Node.js, `node_modules`, `package.json`, `test` and friends will become more relevant. I think we should even add a `src` folder here with sample `html.htl` and `html.pre.js` to show how those can be overlaid.

**Comment by bdelacretaz** [comment]
I see your point - my angle for this Example Zero would be to show only what's strictly needed to publish the website, to show how simple it is: just Markdown files, images, CSS etc, pure content.

Of course, once you start writing code you'll need these things and we can expose them but I think for a minimal example they tend to hide the simplicity of Helix.

So maybe hide them (in a separate branch as suggested, if we can make this work - but that should be possible by merging in the CircleCI script) only for very simple content-only examples such as this one, but not for more advanced examples.

**Comment by bdelacretaz** [comment]
See also my comment in https://github.com/adobe/helix-home/pull/26 about a single vs multiple example repos - for this one I'm shooting for a very small thing with just a few visible content files, to show the impressive simplicity of Helix.

**Comment by rofe** [comment]
I see. If we end up going for multiple repos, it's fine to have a very simple one without `src` folder, and consequently it should also not have any Node related resources or tests imho.

> we might hide those files in a separate branch

I don't think that would be very practical or intuitive. I'd prefer helix-continuous (or maybe a dedicated helix-pages-continuous).
